# Generated by Django 5.2.1 on 2025-05-25 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costprice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20, unique=True)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_type', models.CharField(max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customerid', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_type', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('invoices', models.FileField(blank=True, null=True, upload_to='invoices/')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_w', models.CharField(max_length=255, unique=True)),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_133.costprice')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.CharField(max_length=255)),
                ('quantity_in_stock', models.PositiveIntegerField()),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_status', models.CharField(choices=[('open stock', 'เปิดสต็อก'), ('close stock', 'ปิดสต็อก')], default='open stock', max_length=50)),
                ('manufacture_date', models.DateField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_by_name', to='pos_133.costprice')),
                ('warehouse_w', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_133.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Quatation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pos_133.customer')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pos_133.marketprice')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('sale_quantity', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'รอชำระเงิน'), ('paid', 'ชำระแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=10)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_133.customer')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_133.product')),
                ('sale_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_price_by_product', to='pos_133.marketprice')),
            ],
        ),
    ]
