# Generated by Django 5.2 on 2025-06-07 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_133', '0002_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costprice',
            options={'permissions': [('can_add_costprice', 'Can add cost price'), ('can_view_costprice', 'Can view cost price'), ('can_edit_costprice', 'Can edit cost price'), ('can_delete_costprice', 'Can delete cost price')]},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('can_add_customer', 'Can add customer'), ('can_view_customer', 'Can view customer'), ('can_edit_customer', 'Can edit customer'), ('can_delete_customer', 'Can delete customer')]},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'permissions': [('can_add_expense', 'Can add expense'), ('can_view_expense', 'Can view expense'), ('can_edit_expense', 'Can edit expense'), ('can_delete_expense', 'Can delete expense')]},
        ),
        migrations.AlterModelOptions(
            name='marketprice',
            options={'permissions': [('can_add_marketprice', 'Can add market price'), ('can_view_marketprice', 'Can view market price'), ('can_edit_marketprice', 'Can edit market price'), ('can_delete_marketprice', 'Can delete market price')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_add_product', 'Can add product'), ('can_view_product', 'Can view product'), ('can_edit_product', 'Can edit product'), ('can_delete_product', 'Can delete product')]},
        ),
        migrations.AlterModelOptions(
            name='quatation',
            options={'permissions': [('can_add_quatation', 'Can add quotation'), ('can_view_quatation', 'Can view quotation'), ('can_edit_quatation', 'Can edit quotation'), ('can_delete_quatation', 'Can delete quotation')]},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'permissions': [('can_add_warehouse', 'Can add warehouse'), ('can_view_warehouse', 'Can view warehouse'), ('can_edit_warehouse', 'Can edit warehouse'), ('can_delete_warehouse', 'Can delete warehouse')]},
        ),
    ]
