# Generated by Django 5.2 on 2025-06-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_133', '0003_alter_costprice_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costprice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.AlterModelOptions(
            name='marketprice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quatation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={},
        ),
    ]
