# Generated by Django 5.1.6 on 2025-05-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Format: 133MMYY## (MM=month 01-12, YY=year, ##=sequence 01-99)', max_length=9, null=True, unique=True),
        ),
    ]
